version: '2'
services:
  afrostreampostgres:
    environment:
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./data/postgresql:/var/lib/postgresql/data
    build: ./afrostream-postgres
    ports:
     - "5700:5432"
  rabbitmq:
    environment:
     - RABBITMQ_DEFAULT_USER=rabbitmq
     - RABBITMQ_DEFAULT_PASS=rabbitmq
    image: rabbitmq:3-management
    ports:
     - "5603:15672"
  afrostreamapiv1:
    environment:
     - AFROSTREAM_API_KEY=8c261045-89a3-44bb-af38-65a847269605
     - AFROSTREAM_API_SECRET=3dc3cae6-9c79-487a-9e0f-712be857dcee
     - ALLOW_URL=*
     - API_CLIENT_END_POINT=http://afrostreambackend/api
     - AUTH0_CALLBACK_URL=afrostream-api-v1.herokuapp.com/callback
     - AUTH0_CLIENT_ID=BtSdIqKqfIse0H1dqlpHFJgKIkUG0NpE
     - AUTH0_DOMAIN=afrostream.eu.auth0.com
     - AUTH0_SECRET=KYmL01KW5HczO-XKpltlVUONRCXtynJQ0nFqiGNOsjN9c3RsBAnr5_T-rnnc7DYY
     - KEY_METRICS_PRIVATE_KEY=qigcd3tiue2el5k
     - KEY_METRICS_PUBLIC_KEY=ns4xyu6prfqcarv
     - MONGOLAB_URI=mongodb://heroku_nd0hbtmt:k556bnvhqfc7fbiamm5ub4g7qu@ds047712.mongolab.com:47712/heroku_nd0hbtmt
     - NODE_ENV=development
     - RECURLY_API_KEY=67dbb29f0dbe4e219bc247a3b5387652
     - RECURLY_SUB_DOMAIN=johnarch
     - SESSION_SECRET=afrostream-secret
     - WEB_MACHINE_NAME=heroku
     - IP=0.0.0.0
     - PORT=5601
    build: ./afrostream-api-v1
    ports:
      - "5601:5601"
    volumes:
      - ./src/afrostream-api-v1:/usr/src/app
    depends_on:
      - afrostreambackend
    links:
      - afrostreambackend
  afrostreambackend:
    environment:
      - ALGOLIA_API_KEY=47d48040a13e973aca2ea9f492eca17e
      - ALGOLIA_APP_ID=3OKNPL7ZVA
      - AWS_ACCESS_KEY_ID=AKIAIJ7BEEEIYX3CZDOQ
      - AWS_SECRET_ACCESS_KEY=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
      - CLOUDAMQP_URL=amqp://rabbitmq:rabbitmq@rabbitmq/
      - DATABASE_URL=postgres://postgres:postgres@afrostreampostgres/postgres
      - DIGIBOS_DOMAIN=http://mam.afrostream.tv:3000/api/contents
      - DIGIBOS_PROXY=http://origin.afrostream.tv
      - DIGIBOS_TOKEN=false
      - FACEBOOK_CALLBACK_DOMAIN=https://afrostream.tv
      - FACEBOOK_ID=828887693868980
      - FACEBOOK_SECRET=25130290468ec21fbefd1604218cc57c
      - GRAPHENEDB_URL=http://app39710506-KSSG0x:zU6HMofF9KLiz6FZPbvo@app39710506kssg0x.sb04.stations.graphenedb.com:24789
      - IMGIX_DOMAIN=https://afrostream.imgix.net
      - MONGOLAB_URI=mongodb://heroku_wsgfcwfr:l12bet6hdb39mcvb6vklp9vg3s@ds037581.mongolab.com:37581/heroku_wsgfcwfr
      - NODE_ENV=development
      - RECURLY_API_KEY=82e5ec329c384b4995b979cc63536796
      - RECURLY_SUB_DOMAIN=afrostream
      - S3_BUCKET_NAME=afrostream-img
      - SEND_GRID_API_KEY=Afr@stream77
      - SEND_GRID_CLIENT_ID=azure_3e7c4f32e08f4c0ba3c3ec8eb6c2fe58@azure.com
      - USER_TOKEN_EXPIRE=86400
      - VIDEO_TOKEN_EXPIRE=300
      - IP=0.0.0.0
      - PORT=5602
    build: ./afrostream-back-end
    ports:
      - "5602:5602"
    volumes:
      - ./src/afrostream-back-end:/usr/src/app
    depends_on:
      - afrostreampostgres
      - rabbitmq
    links:
      - afrostreampostgres
      - rabbitmq
  afrostreamfrontend:
    environment:
      - ALGOLIA_API_KEY=3e6547172fb6d80b2ae02d6369edfc72
      - ALGOLIA_APP_ID=3OKNPL7ZVA
      - API_CLIENT_AUTHORITY=api.afrostream.tv
      - API_CLIENT_END_POINT=http://localhost:5601/
      - API_CLIENT_PROTOCOL=http
      - API_END_POINT=http://localhost:5602/
      - API_IMAGES_AUTHORITY=images.cdn.afrostream.net
      - API_IMAGES_END_POINT=https://images.cdn.afrostream.net
      - API_IMAGES_PROTOCOL=https
      - BITLY_ACCESS_TOKEN=3f7014f52dd257e8e502a3682835721020713736
      - BITLY_API_KEY=R_8199c11a3938481aa8fdd538530b9137
      - BITLY_CLIENT_ID=6919ad7c69fc680e8c1746e329ce06ebf4528640
      - BRAINTREE_PUBLIC_KEY=production_f4y3q99v_x6hsrp62xgzbfj98
      - CHROMECAST_ID=
      - DOMAIN_HOST=afrostream.tv
      - FB_TRACKING_ID=914487875264661
      - GA_TRACKING_ID=UA-47871575-1
      - GOCARDLESS_PUBLIC_KEY=CYgpKfDiPnYMvQ5BFGE_3s2IHIaSbSzQ4Tmg2Vsl
      - GOOGLE_ANALYTICS=UA-47871575-1
      - LIBRATO_PASSWORD=89e73b2f58f85ff7
      - LIBRATO_TOKEN=b0b6ff7d039d0576ac3237ed63947292e3025bb942bdddb0f788f6a56023c1ce
      - LIBRATO_USER=app38190314@heroku.com
      - OAUTH_BOUYGUES_ENABLED=true
      - OAUTH_FACEBOOK_ENABLED=true
      - OAUTH_ORANGE_ENABLED=true
      - RECURLY_PUBLIC_KEY=sjc-WOBbERhzqRX5AJ6hVGOPzv
      - SENDBIRD_API_TOKEN=3915d25ef28e538be42206f17ff7345bb7e6a6cb
      - SENDBIRD_APP_ID=BEACEB74-4847-4DB1-94F2-F0F04688392A
      - SENTRY_DSN=https://24502de12b75437cb3783c395bd466f0:0d9f657cbc81459ba70c0ad132536a2d@app.getsentry.com/59853
      - SPONSORSHIP_BILLING_UUID=d9e879c7-e445-409f-ad44-817e30e62fc0
      - STRIPE_PUBLIC_KEY=pk_test_s9YFHvFFIjo2gdAL5x4k2ISh
      - YOUBORA_ID=afrostream
      - NODE_ENV=development
      - WPHOST=0.0.0.0
      - WPPORT=5604
      - IP=0.0.0.0
      - PORT=5600
    ports:
      - "5600:5600"
      - "5604:5604"
    volumes:
      - ./src/afrostream-front-end:/usr/src/app
    build: ./afrostream-front-end
    links:
      - afrostreamapiv1
  afrostreambillings:
    environment:
      - AFR_DB_HOST=
      - AFR_DB_NAME=
      - AFR_DB_PASSWORD=
      - AFR_DB_PORT=
      - AFR_DB_USER=
      - API_HTTP_AUTH_PWD=pwd
      - API_HTTP_AUTH_USER=admin
      - API_HTTP_SECURE=0
      - AWS_ACCESS_KEY_ID=
      - AWS_BUCKET_BILLINGS_EXPORTS=afrostream-exports-billings
      - AWS_ENV=staging
      - AWS_FOLDER_CSVS=csvs
      - AWS_FOLDER_SUBSCRIPTIONS=subscriptions
      - AWS_FOLDER_TRANSACTIONS=transactions
      - AWS_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=
      - AWS_VERSION=latest
      - BILLINGS_ENV=staging
      - BILLINGS_API_URL=
      - BILLINGS_API_HTTP_AUTH_USER=admin
      - BILLINGS_API_HTTP_AUTH_PWD=pwd
      - BOUYGUES_BHA_ACTIVATED=0
      - BOUYGUES_BILLING_SYSTEM_HTTP_AUTH_PWD=pwd
      - BOUYGUES_BILLING_SYSTEM_HTTP_AUTH_USER=admin
      - BOUYGUES_MERCHANTID=0
      - BOUYGUES_PROXY_HOST=proxy.adm.afrostream.net
      - BOUYGUES_PROXY_PORT=3128
      - BOUYGUES_PROXY_PWD=pwd
      - BOUYGUES_PROXY_USER=user
      - BOUYGUES_SERVICEID=0
      - BOUYGUES_SFTP_STATS_HOST=gas.bouyguesbox.fr
      - BOUYGUES_SFTP_STATS_PORT=2222
      - BOUYGUES_SFTP_STATS_USER=svodafrostream
      - BOUYGUES_STORE_LAST_TIME_HOUR=0
      - BOUYGUES_STORE_LAST_TIME_MINUTE=25
      - BOUYGUES_SUBSCRIPTION_PERIOD_LENGTH=1
      - BOUYGUES_TV_API_URL=https://idp.bouygtel.fr:20443/federation/eligibility
      - BOUYGUES_TV_HACK_ACTIVATED=0
      - BRAINTREE_ENVIRONMENT=sandbox
      - BRAINTREE_MERCHANT_ID=vpchhx9ppk3xwrcy
      - BRAINTREE_PRIVATE_KEY=d2cc0c2d62852a9555e7fa9119f89665
      - BRAINTREE_PUBLIC_KEY=hpwk56f69q22bnqh
      - BRAINTREE_TRANSACTION_URL_DETAIL_FORMAT=https://sandbox.braintreegateway.com/merchants/%s/transactions/%s
      - CASHWAY_API_HTTP_AUTH_PWD=81c2c892f30d8304c6af90a387001765132a2887b76a7bdbe39af9131f1be9b9
      - CASHWAY_API_HTTP_AUTH_USER=73123a828c94b4b1f2b4e4669a5cae6e187090ff7ba510d6de449d707e980951
      - CASHWAY_API_URL=https://api-staging.cashway.fr/
      - CASHWAY_COUPON_ONE_BY_USER_FOR_EACH_CAMPAIGN_ACTIVATED=0
      - CASHWAY_COUPON_URL=https://staging-payments-afrostream.cashway.fr/1/b/
      - CASHWAY_USE_STAGING=1
      - CASHWAY_USER_AGENT=afrbillingsapi/1.0
      - CASHWAY_WH_SECRET=DakUdoycsOctoaphObyo
      - CONTEXTS_SWITCH_EXPIRED_DATE_BOUNDARY_TO_COMMON_CONTEXT=2016-11-21 23:59:59
      - DATABASE_URL=postgres://postgres:postgres@afrostreambillingspostgres/postgres
      - EVENT_EMAIL_ACTIVATED=1
      - EVENT_EMAIL_PROVIDERS_EXCEPTION=
      - EXPORTS_DAILY_EMAIL_ACTIVATED=1
      - EXPORTS_DAILY_NUMBER_OF_DAYS=31
      - EXPORTS_EMAIL_FROM=exports@afrostream.tv
      - EXPORTS_EMAIL_FROMNAME=Afrostream Export
      - EXPORTS_MONTHLY_EMAIL_ACTIVATED=1
      - EXPORTS_MONTHLY_FIRST_DAY_OF_MONTH=5
      - EXPORTS_MONTHLY_NUMBER_OF_MONTHS=1
      - EXPORTS_SUBSCRIPTIONS_DAILY_EMAIL_BCCS=
      - EXPORTS_SUBSCRIPTIONS_DAILY_EMAIL_TOS=exports@afrostream.tv
      - EXPORTS_SUBSCRIPTIONS_MONTHLY_EMAIL_BCCS=
      - EXPORTS_SUBSCRIPTIONS_MONTHLY_EMAIL_TOS=exports@afrostream.tv
      - EXPORTS_TRANSACTIONS_DAILY_EMAIL_BCCS=
      - EXPORTS_TRANSACTIONS_DAILY_EMAIL_TOS=exports@afrostream.tv
      - EXPORTS_TRANSACTIONS_MONTHLY_EMAIL_BCCS=
      - EXPORTS_TRANSACTIONS_MONTHLY_EMAIL_TOS=exports@afrostream.tv
      - GOCARDLESS_API_ENV=sandbox
      - GOCARDLESS_API_KEY=YXwxcLeTGwGv3sPd1-CpmNh3nAsqtDfzGuV8_Vji
      - GOCARDLESS_WH_SECRET=secret
      - LOG_REQUESTS_ACTIVATED=1
      - NETSIZE_API_AUTH_KEY=368b8163dca54e64a17ec098d63d2464
      - NETSIZE_API_PRODUCT_TYPE=121
      - NETSIZE_API_SERVICE_ID=1
      - NETSIZE_API_URL=http://qa.pay.netsize.com/API/1.2/
      - NETSIZE_SUBSCRIPTION_PERIOD_LENGTH=1
      - ORANGE_SUBSCRIPTION_PERIOD_LENGTH=1
      - ORANGE_TV_API_URL=https://iosw3sn-ba-rest.orange.com:8443/OTP/API_OTVP_Partners-1/user/v1
      - ORANGE_TV_HTTP_AUTH_PWD=a]ar[9vU
      - ORANGE_TV_HTTP_AUTH_USER=OTP-OTP_AFR
      - PAYPAL_API_CLIENT_ID=
      - PAYPAL_API_SECRET=
      - PROXY_HOST=proxy.adm.afrostream.net
      - PROXY_PORT=3128
      - PROXY_PWD=pwd
      - PROXY_USER=user
      - RECURLY_API_KEY=67dbb29f0dbe4e219bc247a3b5387652
      - RECURLY_API_SUBDOMAIN=johnarch
      - RECURLY_IMPORT_TRANSACTIONS_SLEEPING_TIME_IN_MILLIS=250
      - RECURLY_POSTPONE_ACTIVATED=1
      - RECURLY_POSTPONE_LIMIT_IN=7
      - RECURLY_POSTPONE_LIMIT_OUT=28
      - RECURLY_POSTPONE_TO=10
      - RECURLY_WH_HTTP_AUTH_PWD=pwd
      - RECURLY_WH_HTTP_AUTH_USER=admin
      - RECURLY_WH_REPOST_URLS=
      - SENDGRID_API_KEY=SG.lliM3Gp5QyuqgmQ36iLwLw.u3mP5Ne2PhP5Kohs8MO8rHhlA0Q3GLyZil45b9qgl5E
      - SENDGRID_BCC=
      - SENDGRID_FROM=abonnement@afrostream.tv
      - SENDGRID_FROM_NAME=Tonjé, Fondateur d\'Afrostream
      - SENDGRID_TEMPLATE_COUPON_OFFERED_SPONSORSHIP_NEW=22a2e61c-565f-4270-a9bd-6ec7f592b3ed
      - SENDGRID_TEMPLATE_COUPON_OFFERED_STANDARD_NEW=06e63db8-0cf9-4396-b527-1d9e70bee72b
      - SENDGRID_TEMPLATE_COUPON_OWN_SPONSORSHIP_NEW=9a9a2f5b-d784-46f2-852d-0958185f7dd7
      - SENDGRID_TEMPLATE_COUPON_OWN_STANDARD_NEW=40c8532f-4117-434f-882d-81b4e5e50193
      - SENDGRID_TEMPLATE_SUBSCRIPTION_CANCEL_ID=32685665-87ba-4c67-a726-395b58c2e36b
      - SENDGRID_TEMPLATE_SUBSCRIPTION_ENDED_FP_ID=835e891b-c196-486e-8f0a-64394e62f737
      - SENDGRID_TEMPLATE_SUBSCRIPTION_ENDED_ID=51b5b68f-3fc2-4fb3-b274-ec90d9ccfc20
      - SENDGRID_TEMPLATE_SUBSCRIPTION_NEW_ID=dde84299-e6fe-47a0-909b-1ee11417efe1
      - SENDGRID_TO_IFNULL=null@afrostream.tv
      - SENDGRID_VAR_couponAppliedSentence=La réduction de %couponAmountForDisplay% liée au code promo %couponCode% sera appliquée lors du prélèvement.
      - SLACK_ACTIVATED=0
      - SLACK_GROWTH_CHANNEL=test-channel
      - SLACK_STATS_CHANNEL=test-channel
      - SLACK_STATS_COUPONS_CHANNEL=test-channel
      - SLACK_STATS_TRANSACTIONS_CHANNEL=test-channel
      - STRIPE_API_KEY=sk_test_VaFvskbZOobGZ1L3x1iGwzOk
      - STRIPE_WH_HTTP_AUTH_PWD=pwd
      - STRIPE_WH_HTTP_AUTH_USER=admin
    ports:
      - "5605:80"   
    volumes:
      - ./src/afrostream-billings:/app
    build: ./afrostream-billings
    depends_on:
      - afrostreambillingspostgres
    links:
      - afrostreambillingspostgres
  afrostreambillingspostgres:
    environment:
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./data/billingspostgresql:/var/lib/postgresql/data
    build: ./afrostream-billings-postgres
    ports:
     - "5701:5432"
