version: '2'
services:
  afrostreampostgres:
    environment:
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./data/postgresql:/var/lib/postgresql/data
    build: ./afrostream-postgres
  rabbitmq:
    environment:
     - RABBITMQ_DEFAULT_USER=rabbitmq
     - RABBITMQ_DEFAULT_PASS=rabbitmq
    image: rabbitmq:3-management
    ports:
     - "5603:15672"
  afrostreamapiv1:
    environment:
     - AFROSTREAM_API_KEY=8c261045-89a3-44bb-af38-65a847269605
     - AFROSTREAM_API_SECRET=3dc3cae6-9c79-487a-9e0f-712be857dcee
     - ALLOW_URL=*
     - API_CLIENT_END_POINT=http://afrostream-backend.herokuapp.com/api
     - AUTH0_CALLBACK_URL=afrostream-api-v1.herokuapp.com/callback
     - AUTH0_CLIENT_ID=BtSdIqKqfIse0H1dqlpHFJgKIkUG0NpE
     - AUTH0_DOMAIN=afrostream.eu.auth0.com
     - AUTH0_SECRET=KYmL01KW5HczO-XKpltlVUONRCXtynJQ0nFqiGNOsjN9c3RsBAnr5_T-rnnc7DYY
     - KEY_METRICS_PRIVATE_KEY=qigcd3tiue2el5k
     - KEY_METRICS_PUBLIC_KEY=ns4xyu6prfqcarv
     - MONGOLAB_URI=mongodb://heroku_nd0hbtmt:k556bnvhqfc7fbiamm5ub4g7qu@ds047712.mongolab.com:47712/heroku_nd0hbtmt
     - NODE_ENV=development
     - RECURLY_API_KEY=67dbb29f0dbe4e219bc247a3b5387652
     - RECURLY_SUB_DOMAIN=johnarch
     - SESSION_SECRET=afrostream-secret
     - WEB_MACHINE_NAME=heroku
     - IP=0.0.0.0
     - PORT=5601
     - NO_ASSERT=true
    build: ./afrostream-api-v1
    ports:
      - "5601:5601"
    volumes:
      - ./afrostream-api-v1/src:/usr/src/app
  afrostreambackend:
    environment:
      - ALGOLIA_API_KEY=47d48040a13e973aca2ea9f492eca17e
      - ALGOLIA_APP_ID=3OKNPL7ZVA
      - AWS_ACCESS_KEY_ID=AKIAIJ7BEEEIYX3CZDOQ
      - AWS_SECRET_ACCESS_KEY=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
      - CLOUDAMQP_URL=amqp://rabbitmq:rabbitmq@rabbitmq/
      - DATABASE_URL=postgres://postgres:postgres@afrostreampostgres/postgres
      - DIGIBOS_DOMAIN=http://mam.afrostream.tv:3000/api/contents
      - DIGIBOS_PROXY=http://origin.afrostream.tv
      - DIGIBOS_TOKEN=false
      - FACEBOOK_CALLBACK_DOMAIN=https://afrostream.tv
      - FACEBOOK_ID=828887693868980
      - FACEBOOK_SECRET=25130290468ec21fbefd1604218cc57c
      - GRAPHENEDB_URL=http://app39710506-KSSG0x:zU6HMofF9KLiz6FZPbvo@app39710506kssg0x.sb04.stations.graphenedb.com:24789
      - HEROKU_APP_ID=9b9ca901-b7fd-4230-afdf-babf84a27980
      - HEROKU_APP_NAME=afrostream-backend
      - HEROKU_POSTGRESQL_COPPER_URL=postgres://u9u17sot1un0hr:p6o70uurl15iblacuu0g042e742@ec2-54-217-234-109.eu-west-1.compute.amazonaws.com:5552/d8kcdisl77do4k
      - HEROKU_RELEASE_VERSION=v314
      - HEROKU_SLUG_COMMIT=a07d2bd6e4c285633e9f8115041eeed1f37f1014
      - HEROKU_SLUG_DESCRIPTION=Deploy c2ebd25
      - IMGIX_DOMAIN=https://afrostream.imgix.net
      - MONGOLAB_URI=mongodb://heroku_wsgfcwfr:l12bet6hdb39mcvb6vklp9vg3s@ds037581.mongolab.com:37581/heroku_wsgfcwfr
      - NODE_ENV=development
      - RECURLY_API_KEY=82e5ec329c384b4995b979cc63536796
      - RECURLY_SUB_DOMAIN=afrostream
      - S3_BUCKET_NAME=afrostream-img
      - SEND_GRID_API_KEY=Afr@stream77
      - SEND_GRID_CLIENT_ID=azure_3e7c4f32e08f4c0ba3c3ec8eb6c2fe58@azure.com
      - USER_TOKEN_EXPIRE=86400
      - VIDEO_TOKEN_EXPIRE=300
      - IP=0.0.0.0
      - PORT=5602
    build: ./afrostream-back-end
    ports:
      - "5602:5602"
    volumes:
      - ./afrostream-back-end/src:/usr/src/app
    depends_on:
      - afrostreampostgres
      - rabbitmq
    links:
      - afrostreampostgres
      - rabbitmq
